### ISSUE TITLE
Default settings are not reliable with default/supported cf-d configurations

### ISSUE THREAD

**Issue by ChunyiLyu** [cloudfoundry/cats-concourse-task#5] opened 2017-05-23 00:56 UTC
Release Integration and other teams have seen issues with timeouts when performing the `cf push --no-start` command used in the body and BeforeEach of many tests. The default timeout is thirty seconds, but we've had reports from other teams that even when they've configured this to 60 seconds, this issue hasn't completely gone away.

The failure looks like this:
```
[2017-05-22 23:01:24.27 (UTC)]> cf push CATS-9-APP-3d3c0eb6-30ef-44b5-6 --no-start -b ruby_buildpack -m 256M -p assets/dora -d hermione.cf-app.com 
Creating app CATS-9-APP-3d3c0eb6-30ef-44b5-6 in org CATS-9-ORG-43467814-abaa-46c5-7 / space CATS-9-SPACE-c7069fd4-ebff-4162-4 as CATS-USER-9-2017_05_22-23h00m58.026s...
OK

Creating route cats-9-app-3d3c0eb6-30ef-44b5-6.hermione.cf-app.com...
OK

Binding cats-9-app-3d3c0eb6-30ef-44b5-6.hermione.cf-app.com to CATS-9-APP-3d3c0eb6-30ef-44b5-6...
OK

Uploading CATS-9-APP-3d3c0eb6-30ef-44b5-6...
Uploading app files from: /go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/dora
Uploading 138K, 37 files
Done uploading               

[2017-05-22 23:01:54.27 (UTC)]> cf app CATS-9-APP-3d3c0eb6-30ef-44b5-6 --guid 
7ba8ff9c-0f0c-494e-ae51-7c5f2854212d
```
(Note that the guid request at the end is the beginning of our after-each, the command before having timed out.)

Additionally, they say they've only seen this since their CI moved to GCP. That might be a coincidence; our candidate explanation doesn't account for that as a factor. But it's part of the landscape.

We think that the default node count of `12` is saturating the cc's internal workers. The CLI team tells us that the period between `Done uploading` and the `OK` (and command exiting 0) that we're waiting for is the CLI polling a CC endpoint waiting for an upload app bits job that is doing some kind of resource-matching-related work, and passing the bits on to the blobstore.

The factors here appear to be the number of nodes CATs is running, the length of the "standard" timeout in CATs, the resources available to internal CC workers, the performance of the blobstore, and (potentially) which IaaS the CI worker is running on.

We'd like to see the default configuration of this task matched up with the cf-d such that they reliably pass together without modification.

**Comment by dsabeti** [comment] 2017-05-24 21:46
I've written a [few stories to address this](https://www.pivotaltracker.com/story/show/145790119). The basic idea is:
- Increase the default timeout to reduce flakiness for other teams
- Set up a dedicated environment that runs with the current (smaller) timeout, in a loop. Collect information about the flakiness.

We'll probably want to brainstorm a way to test the actions timing out specifically. For example, if I run `cf push` 10 times serially, what is the average time? How about if I run `cf push` 20 times, in parallel sets of 10? Can we find a simple way to reproduce and measure the issue so that we can take steps to reduce the flakiness?

/cc @rosenhouse

**Comment by heyjcollins** [comment] 2018-06-20 05:00
Hi @ChunyiLyu - I'm doing the cleanup of open issues and wanted to follow up on this since it's been open for over a year.
We've made changes to default timeouts in CATs in the time since this issue was created so I'm wondering if this is still valid?

**Comment by davewalter** [comment] 2019-08-02 16:20
Closing issue since repo has been archived.

**Closed as completed by davewalter** 2019-08-02 16:20 UTC
Labels: accepted
